
namespace Yelo
{
	namespace Memory
	{


		void c_function_interface_system::Initialize()
		{
			WRITE_HOOK_BLOCK_PROCESS(render_sky, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_SKY));
			WRITE_HOOK_BLOCK_PROCESS(render_objects, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_OBJECTS));
			WRITE_HOOK_BLOCK_PROCESS(render_structure, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_STRUCTURE_RENDER_LIGHTMAPS));
			WRITE_HOOK_BLOCK_PROCESS(weather_particle_systems_render, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_WEATHER_PARTICLE_SYSTEMS_RENDER));
			WRITE_HOOK_BLOCK_PROCESS(render_hud, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_INTERFACE_DRAW_SCREEN));
			WRITE_HOOK_BLOCK_PROCESS(render_ui, GET_FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_UI_WIDGETS));
			WRITE_HOOK_BLOCK_PROCESS(render_cursor, GET_FUNC_PTR(CALL_HOOK_RENDER_UI_CURSOR));
			WRITE_HOOK_BLOCK_PROCESS(update_ui_widgets, GET_FUNC_VPTR(CALL_HOOK_UPDATE_UI_WIDGETS));
		}

		void c_function_interface_system::Dispose()
		{
		}
	};
};